---
title: "First Knit"
author: "Larissa vera"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  I attended highschool at highland high school and graduated in 2018. English has always been easier for me math is a challange. In english i received an A and in math i recived a D.
### my answer     
  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer     
I have a macbook air (Apple). On a scale from 1 to 10 I am very knowledgeable when it comes to knowing the difference from a nouse to a keyboard. I prefer a mouse due to my carpool tunnel. So i would say a 8. my home internet is pretty great. 
  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer   
My prefered name is larissa. Its the only thing i know to respond to.
  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
what i would love to achieve in class is to have my desgree in nursing. My goal is to finish nursing coarse at AVC.
  
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
the only foeign country i have been to is mexico and thats about it but would lobve to travel more.i would love to go to japan. no military service nor family members and honestly it scares me so i would not be one to apply.
  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
i did not take math 115 before this is my first time but i already like it alot.i my goal grade would be an A but ill settle for a B. 
  
   
 






  




